# SPDX-FileCopyrightText: 2020 The python-scsi Authors
#
# SPDX-License-Identifier: MIT

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies:
          - toml
-   repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.0
    hooks:
    - id: reuse
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3
